version: "3.9"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build: ./config/php
    links:
      - db
    volumes:
      - ./src:/var/www/html
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "dictionary"
    volumes:
      - ./config/mysql/initdb:/docker-entrypoint-initdb.d
      - ./.tmp/mysql/db-data:/var/lib/mysql
